import Vue from 'vue'
import Vuex from 'vuex'

Vue.use(Vuex)

export default new Vuex.Store({
  state: {
    listeTerrains : [
      {'name': 'terrain11', 'color': '', 'image': 'terrain11.png'},	
      {'name': 'terrain10', 'color': '', 'image': 'terrain10.png'},    
      {'name': 'terrain17', 'color': '', 'image': 'terrain17.png'},
      {'name': 'terrain1', 'color': '', 'image': 'terrain1.png'},
      {'name': 'terrain14', 'color': '', 'image': 'terrain14.png'},
      {'name': 'terrain16', 'color': '', 'image': 'terrain16.png'},
      {'name': 'terrain13', 'color': '', 'image': 'terrain13.png'},
    ],
    listeJoueurs : [
      {'name': 'player7-red', 'image': 'player7-red.png'},
      {'name': 'player7-blue', 'image': 'player7-blue.png'},
      {'name': 'player7-yellow', 'image': 'player7-yellow.png'},  
      {'name': 'player7-black', 'image': 'player7-black.png'},
      {'name': 'player6-red', 'image': 'player6-red.png'},
      {'name': 'player6-blue', 'image': 'player6-blue.png'},
      {'name': 'player6-yellow', 'image': 'player6-yellow.png'},  
      {'name': 'player6-black', 'image': 'player6-black.png'},
      {'name': 'player8-red', 'image': 'player8-red.png'},
      {'name': 'player8-blue', 'image': 'player8-blue.png'},
      {'name': 'player8-yellow', 'image': 'player8-yellow.png'},  
      {'name': 'player8-black', 'image': 'player8-black.png'},
      {'name': 'player9-red', 'image': 'player9-red.png'},
      {'name': 'player9-blue', 'image': 'player9-blue.png'},
      {'name': 'player9-yellow', 'image': 'player9-yellow.png'},  
      {'name': 'player9-black', 'image': 'player9-black.png'},
      {'name': 'player13-red', 'image': 'player13-red.png'},
      {'name': 'player13-blue', 'image': 'player13-blue.png'},
      {'name': 'player13-yellow', 'image': 'player13-yellow.png'},  
      {'name': 'player13-black', 'image': 'player13-black.png'},    
      {'name': 'player14-red', 'image': 'player14-red.png'},
      {'name': 'player14-blue', 'image': 'player14-blue.png'},
      {'name': 'player14-yellow', 'image': 'player14-yellow.png'},  
      {'name': 'player14-black', 'image': 'player14-black.png'},
      {'name': 'player15-red', 'image': 'player15-red.png'},
      {'name': 'player15-blue', 'image': 'player15-blue.png'}, 
      {'name': 'player15-yellow', 'image': 'player15-yellow.png'},  
      {'name': 'player15-black', 'image': 'player15-black.png'}, 
      {'name': 'player16-red', 'image': 'player16-red.png'},
      {'name': 'player16-blue', 'image': 'player16-blue.png'},
      {'name': 'player16-yellow', 'image': 'player16-yellow.png'},  
      {'name': 'player16-black', 'image': 'player16-black.png'}, 
      {'name': 'player17-red', 'image': 'player17-red.png'},
      {'name': 'player17-blue', 'image': 'player17-blue.png'},
      {'name': 'player17-yellow', 'image': 'player17-yellow.png'},  
      {'name': 'player17-black', 'image': 'player17-black.png'}, 
      {'name': 'player19-red', 'image': 'player19-red.png'},
      {'name': 'player19-blue', 'image': 'player19-blue.png'},
      {'name': 'player19-yellow', 'image': 'player19-yellow.png'},  
      {'name': 'player19-black', 'image': 'player19-black.png'}, 
      {'name': 'player11', 'image': 'player11.png'},
      {'name': 'player12', 'image': 'player12.png'},
      {'name': 'player18', 'image': 'player18.png'}, 
      {'name': 'player20', 'image': 'player20.png'},
    ],
    listeJoueurAlig : [
      {'name': 'player9', 'image': 'player9.png'},
      {'name': 'player10', 'image': 'player10.png'},
      {'name': 'player11', 'image': 'player11.png'},
      {'name': 'player12', 'image': 'player12.png'},
      {'name': 'player5', 'image': 'player5.png'},
      {'name': 'player6', 'image': 'player6.png'},
      {'name': 'player7', 'image': 'player7.png'},
      {'name': 'player8', 'image': 'player8.png'},
      {'name': 'player13', 'image': 'player13.png'},
      {'name': 'player14', 'image': 'player14.png'},
      {'name': 'player15', 'image': 'player15.png'},
      {'name': 'player16', 'image': 'player16.png'},
    ],
    listeTerrainsAlig : [
      {'name': 'terrain2', 'color': '', 'image': 'terrain2.png'},	
      {'name': 'terrain1', 'color': '', 'image': 'terrain1.png'},	
      {'name': 'terrain3', 'color': '', 'image': 'terrain3.png'},	
      {'name': 'terrain4', 'color': '', 'image': 'terrain4.png'},	
      {'name': 'terrain5', 'color': '', 'image': 'terrain5.png'},	
      {'name': 'terrain6', 'color': '', 'image': 'terrain6.png'},	
      {'name': 'terrain7', 'color': '', 'image': 'terrain7.png'},	   
      {'name': 'terrain8', 'color': '', 'image': 'terrain8.png'},	
    ],
    listeOutils : [
      {'name': 'ballon', 'image': 'ballon.png'}, 
      {'name': 'source_ballon', 'image': 'source_ballon.png'},
      {'name': 'but', 'image': 'but.png'},    	
      {'name': 'but3', 'image': 'but3.png'},
      {'name': 'but2', 'image': 'but2.png'},
      {'name': 'cone', 'image': 'cone.png'},
      {'name': 'cone-red', 'image': 'cone-red.png'},
      {'name': 'cone-blue-claro', 'image': 'cone-blue-claro.png'},
      {'name': 'cone-yellow', 'image': 'cone-yellow.png'},
      {'name': 'cone2', 'image': 'cone2.png'},
      {'name': 'cone2-red', 'image': 'cone2-red.png'},
      {'name': 'cone2-blue-claro', 'image': 'cone2-blue-claro.png'},
      {'name': 'cone2-yellow', 'image': 'cone2-yellow.png'},
      {'name': 'stair', 'image': 'stair.png'},
      {'name': 'stair-left', 'image': 'stair-left.png'},
      {'name': 'hoop', 'image': 'hoop.png'},
      {'name': 'hoop-red', 'image': 'hoop-red.png'},
      {'name': 'hoop-blue-claro', 'image': 'hoop-blue-claro.png'},
      {'name': 'hoop-yellow', 'image': 'hoop-yellow.png'},
      {'name': 'flag-black', 'image': 'flag-black.png'},
      {'name': 'flag-red', 'image': 'flag-red.png'},
      {'name': 'hurdles-black', 'image': 'hurdles-black.png'},
      {'name': 'hurdles-red', 'image': 'hurdles-red.png'},
      {'name': 'blocking', 'image': 'blocking.png'},
      {'name': 'blocking-red', 'image': 'blocking-red.png'},
      {'name': 'pick', 'image': 'pick.png'},   
      {'name': 'pic-red', 'image': 'pick-red.png'},
    ],
    listeLignes : [
      {'name': 'terrain7-2lignes', 'image': 'terrain7-2lignes.png', 'options':[{'image':'terrain7-2lignes_2color'}], 'terrain':'terrain7'}, 
      {'name': 'terrain7-3lignes', 'image': 'terrain7-3lignes.png', 'options':[{'image':'terrain7-3lignes_2colors'}], 'terrain':'terrain7'}, 
      {'name': 'terrain7-4lignes', 'image': 'terrain7-4lignes.png', 'options':[{'image':'terrain7-4lignes_2colors'}, {'image':'terrain7-4lignes_4colors'},
        {'image':'terrain7-4lignes_5colors'}], 'terrain':'terrain7'}, 
      {'name': 'terrain7-5lignes', 'image': 'terrain7-5lignes.png', 'options':[], 'terrain':'terrain7'}, 
      {'name': 'terrain7-3lignes-h', 'image': 'terrain7-3lignes-h.png', 'options':[{'image':'c'}, {'image':'terrain7-3lignes-h_3colors'}], 'terrain':'terrain7'}, 
      {'name': 'terrain7-2lignes-h', 'image': 'terrain7-2lignes-h.png', 'options':[], 'terrain':'terrain7'}, 
      {'name': 'terrain7-rectangle1', 'image': 'terrain7-rectangle1.png', 'options':[{'image':'terrain7-rectangle1_colors2'}], 'terrain':'terrain7'},
      {'name': 'terrain7-diago1', 'image': 'terrain7-diago1.png', 'options':[{'image':'terrain7-diago1_2colors'}], 'terrain':'terrain7'}, 
      {'name': 'terrain7-diago2', 'image': 'terrain7-diago2.png', 'options':[{'image':'terrain7-diago2_2colors'}], 'terrain':'terrain7'},
      {'name': 'terrain11-carre', 'image': 'terrain11-carre.png', 'options':[], 'terrain':'terrain11'},
      {'name': 'terrain11-carre_2lignes-v', 'image': 'terrain11-carre_2lignes-v.png', 'options':[], 'terrain':'terrain11'}, 
      {'name': 'terrain11-carre_2lignes-v_2colors', 'image': 'terrain11-carre_2lignes-v_2colors.png', 'options':[], 'terrain':'terrain11'}, 
      {'name': 'terrain11-carre_4lignes', 'image': 'terrain11-carre_4lignes.png', 'options':[], 'terrain':'terrain11'}, 
      {'name': 'terrain11-carre_3lignes-v', 'image': 'terrain11-carre_3lignes-v.png', 'options':[], 'terrain':'terrain11'}, 
      {'name': 'terrain11-carre_3lignes-v_2colors', 'image': 'terrain11-carre_3lignes-v_2colors.png', 'options':[], 'terrain':'terrain11'},
      {'name': 'terrain10-3lignes-v', 'image': 'terrain10-3lignes-v.png', 'options':[], 'terrain':'terrain10'},
      {'name': 'terrain10-3lignes-v_2colors', 'image': 'terrain10-3lignes-v_2colors.png', 'options':[], 'terrain':'terrain10'},
      {'name': 'terrain10-zonesPressing', 'image': 'terrain10-zonesPressing.png', 'options':[], 'terrain':'terrain10'},
      {'name': 'terrain10-3lignes-h', 'image': 'terrain10-3lignes-h.png', 'options':[], 'terrain':'terrain10'},
      {'name': 'terrain10-3lignes-h_2colors', 'image': 'terrain10-3lignes-h_2colors.png', 'options':[], 'terrain':'terrain10'},
    ],
    listeFormes : [
      {'name': 'square-transparent', 'image': 'square-transparent.png', 'forme': 'square'},
      {'name': 'rectangle-black', 'image': 'rectangle-black.png', 'forme': 'rectangle'},
      {'name': 'arrow6', 'image': 'arrow6.png', 'forme': ''},
      {'name': 'arrow15', 'image': 'arrow15.png', 'forme': ''},
      {'name': 'arrow29', 'image': 'arrow29.png', 'forme': ''},
      {'name': 'arrow9', 'image': 'arrow9.png', 'forme': ''},
      {'name': 'arrow31', 'image': 'arrow31.png', 'forme': ''},
      {'name': 'arrow11', 'image': 'arrow11.png', 'forme': ''},
      {'name': 'arrow32', 'image': 'arrow32.png', 'forme': ''},
      {'name': 'arrow28', 'image': 'arrow28.png', 'forme': ''},
      {'name': 'arrow30', 'image': 'arrow30.png', 'forme': ''},
      {'name': 'arrow17', 'image': 'arrow17.png', 'forme': ''},
      {'name': 'arrow20', 'image': 'arrow20.png', 'forme': ''},
      {'name': 'arrow25', 'image': 'arrow25.png', 'forme': ''},
      {'name': 'arrow24', 'image': 'arrow24.png', 'forme': ''},
      {'name': 'arrow26', 'image': 'arrow26.png', 'forme': ''},
      {'name': 'arrow27', 'image': 'arrow27.png', 'forme': ''},
      {'name': 'line1', 'image': 'line1.png', 'forme': ''},
      {'name': 'line1-left', 'image': 'line1-left.png', 'forme': ''},
      {'name': 'line2', 'image': 'line2.png', 'forme': ''},
      {'name': 'line2-left', 'image': 'line2-left.png', 'forme': ''},
    ],
    modePresentation:false,
    showModePresentation:false,
    spinner:{
      showSpinner:false,
      textSpinner:'Téléchargement de l\'image en cours ...',
    },
    imageBase64:undefined,
    showMenuLeft:false,
  },
  getters:{
  },
  mutations: {
    setModePresentationStore(store, value){
      store.modePresentation = value;
    },
    setShowModePresentation(store, value){
      store.showModePresentation = value;
    },
    setShowSpinner(store, value){
      store.spinner.showSpinner = value;
    },
    setTextSpinner(store, value){
      store.spinner.textSpinner = value;
    },
    setImageBase64(store, image){
      store.imageBase64 = image;
    },
    setShowMenuLeft(store, value){
      store.showMenuLeft = value;
    }
  },
  actions: {
  },
  modules: {
  }
})
